
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 03 16:56:29 CST 2017
//----------------------------------------------------

package Gramaticas;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int continuar = 42;
  public static final int bool_t = 24;
  public static final int suma = 4;
  public static final int resta = 5;
  public static final int incluir_hk = 30;
  public static final int abre_llave = 61;
  public static final int no_igual = 18;
  public static final int abre_cor = 66;
  public static final int entero_t = 20;
  public static final int igual_igual = 19;
  public static final int coma = 68;
  public static final int abre_par = 64;
  public static final int igual = 63;
  public static final int decimal_t = 21;
  public static final int multiplicacion = 2;
  public static final int dondecada = 49;
  public static final int inicio = 34;
  public static final int caracter = 54;
  public static final int seleccion = 39;
  public static final int als = 33;
  public static final int dos_puntos = 69;
  public static final int si = 35;
  public static final int mientras = 40;
  public static final int mas_mas = 8;
  public static final int importar = 29;
  public static final int numero = 52;
  public static final int defecto = 38;
  public static final int caracter_t = 22;
  public static final int protegido = 28;
  public static final int columna = 46;
  public static final int menor = 14;
  public static final int var = 13;
  public static final int dondetodo = 50;
  public static final int EOF = 0;
  public static final int llamarhk = 32;
  public static final int mayor_igual = 16;
  public static final int verdadero = 57;
  public static final int para = 41;
  public static final int llamar = 31;
  public static final int procesar = 47;
  public static final int error = 1;
  public static final int publico = 26;
  public static final int mayor = 15;
  public static final int or = 9;
  public static final int datos = 51;
  public static final int punto = 59;
  public static final int vacio = 25;
  public static final int menor_igual = 17;
  public static final int cadena_t = 23;
  public static final int id = 55;
  public static final int xor = 11;
  public static final int potencia = 3;
  public static final int falso = 58;
  public static final int caso = 37;
  public static final int graphikar_funcion = 45;
  public static final int donde = 48;
  public static final int privado = 27;
  public static final int and = 10;
  public static final int not = 12;
  public static final int terminar = 43;
  public static final int cierra_cor = 67;
  public static final int cierra_llave = 62;
  public static final int menos_menos = 7;
  public static final int division = 6;
  public static final int cierra_par = 65;
  public static final int interrogacion = 60;
  public static final int decimal = 53;
  public static final int retorno = 44;
  public static final int cadena = 56;
  public static final int sino = 36;
}

